@startuml
left to right direction
skinparam packageStyle rectangle

actor "Funcionário" as Funcionario

rectangle "Tracker" {

    usecase "Fazer login" as fazerLogin
    usecase "Fazer logout" as fazerLogout


    usecase "Visualizar cards" as visualizarCards
    usecase "Iniciar card" as iniciarCard
    usecase "Pausar card" as pausarCard
    usecase "Finalizar card" as finalizarCard
    usecase "Adicionar descrição" as adicionarDescricao

}

Funcionario --> fazerLogin
Funcionario --> fazerLogout

Funcionario --> visualizarCards

Funcionario --> iniciarCard
Funcionario --> pausarCard
Funcionario --> finalizarCard

pausarCard .> iniciarCard : <<include>>
finalizarCard .> iniciarCard : <<include>>

pausarCard .> adicionarDescricao : <<include>>
finalizarCard .> adicionarDescricao : <<include>>

@enduml