@startuml
left to right direction

class Usuario {
    - id
    - nome
    - CPF
    - email
    - telefone
    - login
    - senha
    - salario
    + login()
    + logout()
}

class Gerente { 
    - setorResponsavel
    
    + cadastrarGerente()
    + editarDadosPessoais()
    + removerGerente()
    + verDadosGerente()
}

class Funcionario {
    - funcao
    - cargaHoraria

    + criarFuncionario()
    + verDadosFuncionario()
    + editarDadosFuncionario()
    + removerFuncionario()
}

class Card {
    - id
    - titulo
    - descricao
    - dataCriacao
    - dataConclusao
    - tags: Tag
    - status: Status
    - funcionario: Funcionario
    + iniciarCard()
    + concluirCard()
    + pausarCard()
}

class Tag {
    - id
    - nome
    + criarTag()
    + editarTag()
    + atribuirTag()
    + removerTag()
}

class Status {
    - id
    - status
    + criarStatus()
    + atualizarStatus()
    + editarStatus()
    + removerStatus()
}

class Relatorio {
    - id
    - titulo
    - dataGeracao
    - gerente: Gerente
    + gerar()
    + filtrarPorFuncionario()
    + filtrarPorPeriodo()
    + filtrarPorTag()
    + calcularDesempenho()
}
Usuario <|-- Gerente
Usuario <|-- Funcionario
Gerente "1" -- "0..*" Funcionario : gerencia >
Funcionario "1" *-- "0..*" Card : possui >
Card "0..*" -- "0..*" Tag : possui >
Card "1" -- "1" Status : possui >
Gerente "1" -- "0..*" Relatorio : gera >
@endum