@startuml
left to right direction

actor Gerente

rectangle "Sistema Tracker" {

    (Login) as UC1
    (Logout) as UC2

    (Gerenciar Funcionários) as UC3
    (Cadastrar Funcionário) as UC4
    (Visualizar Funcionários) as UC5
    (Editar Funcionário) as UC6
    (Remover Funcionário) as UC7

    (Visualizar Cards) as UC8
    (Ver Status) as UC10

    (Gerar Relatórios) as UC11
    (Filtrar Relatórios) as UC12
    (Criar Card) as UC13
    (Atribuir Card a Funcionário) as UC14
    (Adicionar Tag) as UC15

}

Gerente --> UC1
Gerente --> UC2
Gerente --> UC3
Gerente --> UC8
Gerente --> UC11
Gerente --> UC13

UC3 <.. UC4 : <<extend>>
UC3 <.. UC5 : <<extend>>
UC3 <.. UC6 : <<extend>>
UC3 <.. UC7 : <<extend>>


UC8 <.. UC10 : <<extend>>

UC11 <.. UC12 : <<extend>>

UC13 ..> UC14 : <<include>>

UC13 <.. UC15 : <<extend>>

@enduml